
SERVICE_HOST: localhost
SERVICE_PORT: 8080
SQL_DB_HOST: localhost
SQL_DB_PORT: 5433
SQL_DB_USER: postgres
SQL_DB_PASS: 123456
#server:
#  servlet:
#    context-path: '/baseweb'

spring:
  servlet:
    multipart:
     max-file-size: 10MB
     max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SQL_DB_HOST}:${SQL_DB_PORT}/baseweb

    username: ${SQL_DB_USER}
    password: ${SQL_DB_PASS}
  data:
    rest:
      base-path: /api

logging:
  file:
    path: logs
    name: base.log
  level:
    root: INFO
    com:
      dailyopt :
        tripplanning : DEBUG
    org:
      springframework: INFO
  config: classpath:logback-dev.xml
